[package]
name = "raw-image-viewer"
description = "A tool to help identifying an unknown image file format"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["image"] }
rfd = "0.15.3"
